export const LOGIN_PATH = '/login'
export const EVENTI_PATH = '/events'
export const INFO_APP_PATH = '/infoAMusic'
export const PROFILE_PATH = '/profile'
export const FRIENDS_LIST_PATH = '/friendList'
